# Splunk Universal Forwarder inputs.conf
# Deployed on Windows 11 endpoint (C:\Program Files\SplunkUniversalForwarder\etc\system\local\)
# Collects Windows Event Logs + Sysmon telemetry, forwards to indexer on 9997

[WinEventLog://Security]
disabled = 0
index = wineventlog

[WinEventLog://System]
disabled = 0
index = wineventlog

[WinEventLog://Application]
disabled = 0
index = wineventlog

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
index = wineventlog
renderXml = true
